name: Deploy Strapi Backend

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'

          set -e

          cd /home/shayon/uncharted-with-shayon/server

          docker compose pull
          docker compose up -d --remove-orphans

          EOF